# https://www.mkdocs.org/
site_name: Documentation de conception
site_description: Documentation de conception
site_author: Toucan Fortuné
repo_url: https://github.com/toucan-fortune/manuel/tree/main
repo_name: toucan-fortune/manuel

nav:
  - Accueil: index.md
  - Description et diagramme: description.md
  - Manuel de l'utilisateur: manuel.md
  - Sources et codes: sources.md

plugins:
  - search:
      lang: fr

extra_css:
    - docs/custom.css
    
theme:
  # https://squidfunk.github.io/mkdocs-material/
  name: material
  icon:
    repo: fontawesome/brands/github
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: amber
      accent: green
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: amber
      accent: green
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  font:
    text: Roboto
    code: Roboto Mono
  language: fr
  logo: img/android-chrome-192x192.jpg
  favicon: img/favicon.ico
  features:
    #- navigation.sections
    #- navigation.expand
    - toc.follow 
    - toc.integrate
    - navigation.top
    - content.action.view

markdown_extensions:
  # https://squidfunk.github.io/mkdocs-material/reference
  # https://squidfunk.github.io/mkdocs-material/reference/admonitions/
  - abbr
  - admonition
  - def_list
  - footnotes
  - tables
  - toc:
      permalink: true
  # https://squidfunk.github.io/mkdocs-material/setup/extensions/python-markdown-extensions/
  - pymdownx.details  # admonition
  - pymdownx.caret  # ^ ^
  - pymdownx.tilde  # ~ ~
  - pymdownx.keys  # keys
  